#!/bin/sh

if [ $# -ne 2 ]; then
    echo 'Must have 2 arguments: install [DAY] [PART]'
    exit 1
fi

DAY=${1}
PART=${2}

SOURCE_PATH=./day-${DAY}/Part${PART}.hs
BIN_PATH=bin/d${DAY}p${PART}

CWD=$(dirname ${0})

hindent ${SOURCE_PATH}
hlint ${SOURCE_PATH}

mkdir -p bin

stack ghc \
    --cwd ${CWD} \
    -- ${SOURCE_PATH} \
    -o ${BIN_PATH}

